include:
  - docker-compose.yml

services:

  frontend:
    build:
      target: production
    container_name: frontend-prod
    volumes:
      - frontend_build:/usr/share/nginx/html

  # === Backend Microservices ===

  gateway:
    build:
      target: production
    container_name: gateway-prod
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_ROLE_ID: ${VAULT_ROLE_ID}
      VAULT_SECRET_ID: ${VAULT_SECRET_ID}
      VAULT_MAX_RETRIES: "30"
    depends_on:
      vault:
        condition: service_healthy
    expose:
      - "3002"

  core:
    build:
      target: production
    container_name: core-prod
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_ROLE_ID: ${VAULT_ROLE_ID}
      VAULT_SECRET_ID: ${VAULT_SECRET_ID}
      VAULT_MAX_RETRIES: "30"
    depends_on:
      vault:
        condition: service_healthy
    expose:
      - "3000"

  auth:
    build:
      target: production
    container_name: auth-prod
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_ROLE_ID: ${VAULT_ROLE_ID}
      VAULT_SECRET_ID: ${VAULT_SECRET_ID}
      VAULT_MAX_RETRIES: "30"
    depends_on:
      vault:
        condition: service_healthy
    expose:
      - "3001"

  game:
    build:
      target: production
    container_name: game-prod
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_ROLE_ID: ${VAULT_ROLE_ID}
      VAULT_SECRET_ID: ${VAULT_SECRET_ID}
      VAULT_MAX_RETRIES: "30"
    depends_on:
      vault:
        condition: service_healthy
    expose:
      - "3003"

  # === Infrastructure ===

  db:
    container_name: db-prod
    expose:
      - "5432"
    volumes:
      - db_data_prod:/var/lib/postgresql/data

  migration:
    container_name: migration-prod

  nginx:
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      frontend:
        condition: service_completed_successfully
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./nginx/cert:/etc/nginx/cert:ro

  # === Vault ===

  vault:
    image: hashicorp/vault:latest
    container_name: vault-prod
    cap_add:       # https://man7.org/linux/man-pages/man7/capabilities.7.html
      - IPC_LOCK   # Enable memory lock (mlock) to prevent memory swap (writing memory to disk).
    command: vault server -config=/vault/config/vault.hcl
    volumes:
      - ./vault/config/vault.hcl:/vault/config/vault.hcl:ro # ro - read only mode, not modifying in runtime.
      - vault_data:/vault/file
    ports:
      - "127.0.0.1:8200:8200"
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8200/v1/sys/health 2>/dev/null | grep -q '\"sealed\":false'"]
      interval: 5s
      timeout: 3s
      start_period: 10s
      retries: 5

volumes:
  db_data_prod:
  frontend_build:
  vault_data:
