include:
  - docker-compose.yml

services:

  frontend:
    build:
      target: development
    container_name: frontend-dev
    env_file:
      - path: ./.env
        required: false
    volumes:
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/vite.config.js:/app/vite.config.js:ro
      - ./frontend/public:/app/public:rw
      - ./frontend/src:/app/src:rw
    ports:
      - "5173:5173"

  # === Backend Microservices ===

  gateway:
    build:
      target: development
    container_name: gateway-dev
    env_file:
      - path: ./.env
        required: false
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: dev-root-token
    depends_on:
      vault:
        condition: service_healthy
    ports:
      - "3002:3002"
    volumes:
      - ./backend/gateway/src:/app/src:ro
      - ./backend/gateway/package.json:/app/package.json:ro
      - ./backend/gateway/tsconfig.json:/app/tsconfig.json:ro
      - ./backend/gateway/nest-cli.json:/app/nest-cli.json:ro

  core:
    build:
      target: development
    container_name: core-dev
    env_file:
      - path: ./.env
        required: false
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: dev-root-token
    depends_on:
      vault:
        condition: service_healthy
    volumes:
      - ./backend/core/src:/app/src:ro
      - ./backend/core/package.json:/app/package.json:ro
      - ./backend/core/tsconfig.json:/app/tsconfig.json:ro
      - ./backend/core/nest-cli.json:/app/nest-cli.json:ro
      - ./common/db-entities/dist:/app/db-entities-dist:ro
    ports:
      - "3000:3000"

  auth:
    build:
      target: development
    container_name: auth-dev
    env_file:
      - path: ./.env
        required: false
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: dev-root-token
    depends_on:
      vault:
        condition: service_healthy
    ports:
      - "3001:3001"
    volumes:
      - ./backend/auth/src:/app/src:ro
      - ./backend/auth/package.json:/app/package.json:ro
      - ./backend/auth/tsconfig.json:/app/tsconfig.json:ro
      - ./backend/auth/nest-cli.json:/app/nest-cli.json:ro
      - ./common/db-entities/dist:/app/db-entities-dist:ro

  game:
    build:
      target: development
    container_name: game-dev
    env_file:
      - path: ./.env
        required: false
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: dev-root-token
    depends_on:
      vault:
        condition: service_healthy
    ports:
      - "3003:3003"
    volumes:
      - ./backend/game/src:/app/src:ro
      - ./backend/game/package.json:/app/package.json:ro
      - ./backend/game/tsconfig.json:/app/tsconfig.json:ro
      - ./backend/game/nest-cli.json:/app/nest-cli.json:ro

  migration:
    container_name: migration-dev
    env_file:
      - path: ./.env
        required: false
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: transcendence
      POSTGRES_DB: transcendence
    volumes:
      - ./backend/migration/data-source.ts:/app/data-source.ts:ro
      - ./backend/migration/migrations:/app/migrations:ro
      - ./backend/migration/package.json:/app/package.json:ro
      - ./backend/migration/tsconfig.json:/app/tsconfig.json:ro
      - ./common/db-entities/dist:/app/db-entities-dist:ro

  # === Infrastructure ===

  vault:
    container_name: vault-dev
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"

  db:
    container_name: db-dev
    env_file:
      - path: ./.env
        required: false
    environment:
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: transcendence
      POSTGRES_DB: transcendence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transcendence -d transcendence || exit 1"]
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data

  nginx:
    container_name: nginx-dev
    env_file:
      - path: ./.env
        required: false
    environment:
      NODE_ENV: development
      FRONTEND_URL: http://localhost:8080
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:8080 || exit 1"]
    ports:
      # - "80:80" // comment out port for compatability with hive's computers
      - "8080:8080"

volumes:
  db_data_dev:
